# Generated by Django 4.1.7 on 2023-03-05 22:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_ticket_number_ticket_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='number',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='seat',
        ),
        migrations.AddField(
            model_name='ticket',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='ticket',
            name='event_name',
            field=models.CharField(default='asdf', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ticket',
            name='location',
            field=models.CharField(default='asdfasdf', max_length=200),
            preserve_default=False,
        ),
    ]
