# Generated by Django 4.1.7 on 2023-03-06 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_concert_ticket_concert'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='concert',
        ),
    ]
