# Generated by Django 4.1.7 on 2023-03-06 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_concert_api_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='concert',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='main_app.concert'),
            preserve_default=False,
        ),
    ]
