# Generated by Django 4.1.7 on 2023-03-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_ticket_concert'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='bought',
            field=models.BooleanField(default=False),
        ),
    ]
